"use client";

import React, { createContext, useContext, ReactNode } from "react";

// Chỉ giữ ngôn ngữ tiếng Việt
export type Language = "vi";

// Định nghĩa kiểu dữ liệu cho translations
type TranslationValue = string;

export type Translations = {
  [key: string]: TranslationValue;
};

// Tạo translations chỉ với tiếng Việt
export const translations: Translations = {
  dashboard: "Bảng điều khiển",
  "dashboard.title": "Bảng điều khiển",
  addTrade: "Thêm giao dịch",
  history: "Lịch sử",
  "tradeHistory.title": "Lịch Sử Giao Dịch",
  "tradeHistory.description": "Xem và quản lý tất cả hoạt động giao dịch của bạn",
  "tradeHistory.searchPlaceholder": "Tìm kiếm giao dịch...",
  "tradeHistory.newTrade": "Giao Dịch Mới",
  "tradeHistory.openTrades": "Giao Dịch Mở",
  "tradeHistory.closedTrades": "Giao Dịch Đóng",
  "tradeHistory.winRate": "Tỷ Lệ Thắng",
  "tradeHistory.totalPL": "Tổng Lãi/Lỗ",
  "tradeHistory.allTrades": "Tất Cả GD",
  "tradeHistory.open": "Đang Mở",
  "tradeHistory.closed": "Đã Đóng",
  "tradeHistory.columns": "Cột",
  "tradeHistory.noopenTradesFound": "Không tìm thấy giao dịch mở nào",
  "tradeHistory.noclosedTradesFound": "Không tìm thấy giao dịch đóng nào",
  "tradeHistory.noOpenTradesMessage": "Bạn không có giao dịch mở nào. Thêm giao dịch không có ngày thoát.",
  "tradeHistory.noClosedTradesMessage": "Bạn không có giao dịch đóng nào. Thêm thông tin thoát cho các giao dịch mở của bạn.",
  "tradeHistory.noResultsFound": "Không tìm thấy kết quả",
  "tradeHistory.noMatchingTrades": "Không có giao dịch nào khớp với tiêu chí tìm kiếm của bạn",
  "tradeHistory.clearFilters": "Xóa bộ lọc",
  "tradeHistory.showing": "Hiển thị {filtered} trong tổng số {total} giao dịch",
  "tradeHistory.noTradesYet": "Chưa Có Giao Dịch Nào",
  "tradeHistory.startByAdding": "Bắt đầu bằng cách thêm giao dịch đầu tiên để xem lịch sử của bạn.",
  "tradeHistory.addNewTrade": "Thêm Giao Dịch Mới",
  "tradeForm.title.add": "Thêm Giao Dịch",
  "tradeForm.title.edit": "Sửa Giao Dịch",
  "app.name": "Nhật ký Giao dịch",
  "button.addTrade": "Thêm Giao Dịch",
  settings: "Cài đặt",
  account: "Tài khoản",
  language: "Ngôn ngữ",
  english: "Tiếng Anh",
  vietnamese: "Tiếng Việt",
  accountGrowth: "Tăng trưởng tài khoản",
  performance: "Hiệu suất",
  winRate: "Tỷ lệ thắng",
  profitFactor: "Hệ số lợi nhuận",
  averageWin: "Lợi nhuận trung bình",
  averageLoss: "Thua lỗ trung bình",
  symbol: "Mã giao dịch",
  entryPrice: "Giá vào lệnh",
  exitPrice: "Giá thoát lệnh",
  direction: "Hướng",
  size: "Khối lượng",
  profit: "Lợi nhuận",
  date: "Ngày",
  notes: "Ghi chú",
  save: "Lưu",
  cancel: "Hủy",
  "tradeForm.selectPlaybook": "Chọn chiến lược",
  timeframe: "Khung thời gian",
  tradeSetup: "Thiết lập giao dịch",
  long: "Mua",
  short: "Bán",
  "dashboard.welcome": "Chào mừng đến với Trade Insights!",
  "dashboard.noTrades": "Có vẻ như bạn chưa thêm giao dịch nào.",
  "dashboard.getStarted": "Bắt đầu bằng cách thêm giao dịch đầu tiên để xem bảng điều khiển hiệu suất của bạn.",
  "dashboard.addFirstTrade": "Thêm Giao Dịch Đầu Tiên",
  "dashboard.loadDemoData": "Tải Dữ Liệu Mẫu",
  "dashboard.refreshDemoData": "Làm Mới Dữ Liệu Mẫu",
  "dashboard.overview": "Tổng Quan",
  "dashboard.advancedAnalytics": "Phân Tích Nâng Cao",
  "dashboard.openPositions": "Vị Thế Mở",
  "dashboard.openPositionsMessage": "Bạn có {count} giao dịch mở. Số liệu thống kê dưới đây chỉ dựa trên các giao dịch đã đóng.",
  "dashboard.7days": "7 Ngày",
  "dashboard.30days": "30 Ngày",
  "dashboard.90days": "90 Ngày",
  "dashboard.allTime": "Tất Cả",
  "dashboard.totalPL": "Tổng Lãi/Lỗ",
  "dashboard.winRate": "Tỷ Lệ Thắng",
  "dashboard.avgTradeDuration": "Thời Gian Giao Dịch TB",
  "dashboard.days": "ngày",
  "dashboard.totalClosedTrades": "Tổng Giao Dịch Đã Đóng",
  "dashboard.winningTrades": "Giao Dịch Thắng",
  "dashboard.losingTrades": "Giao Dịch Thua",
  "dashboard.viewAdvancedAnalytics": "Xem Phân Tích Nâng Cao",
  "dashboard.manageJournals": "Quản lý Nhật ký",
  "trade.date": "Ngày",
  "trade.entryTime": "Giờ Vào",
  "trade.exitTime": "Giờ Ra",
  "trade.symbol": "Mã CP",
  "trade.direction": "Hướng",
  "trade.long": "Mua",
  "trade.short": "Bán",
  "trade.quantity": "Số Lượng",
  "trade.price": "Giá",
  "trade.stopLoss": "Dừng Lỗ",
  "trade.takeProfit": "Chốt Lời",
  "trade.fees": "Phí",
  "trade.setup": "Chiến lược",
  "trade.risk": "Rủi Ro",
  "trade.mood": "Cảm Xúc",
  "trade.rating": "Đánh Giá",
  "trade.pl": "Lãi/Lỗ",
  "trade.editTrade": "Sửa giao dịch",
  "trade.deleteTrade": "Xóa giao dịch",
  "trade.confirmDeleteTitle": "Bạn có chắc không?",
  "trade.confirmDeleteDescription": "Hành động này không thể hoàn tác. Giao dịch cho {symbol} sẽ bị xóa vĩnh viễn.",
  "trade.cancel": "Hủy",
  "trade.delete": "Xóa",
  "pagination.previous": "Trước",
  "pagination.next": "Tiếp",
  "sidebar.dashboard": "Bảng điều khiển",
  "sidebar.tradeHistory": "Lịch sử giao dịch",
  "sidebar.addNewTrade": "Thêm giao dịch mới",
  "sidebar.playbooks": "Chiến lược",
  "sidebar.support": "Hỗ trợ",
  "sidebar.helpCenter": "Trung tâm trợ giúp",
  "sidebar.helpDocumentation": "Trợ giúp & Tài liệu",
  "sidebar.settings": "Cài đặt",
  "sidebar.collapseSidebar": "Thu gọn thanh bên",
  "sidebar.expandSidebar": "Mở rộng thanh bên",
  "sidebar.journals": "Nhật ký",
  "sidebar.mainNavigation": "Điều hướng chính",
  "sidebar.quickActions": "Thao tác nhanh",
  "tradeForm.description": "Ghi lại chi tiết giao dịch để theo dõi và phân tích tốt hơn",
  "tradeForm.back": "Quay lại",
  "tradeForm.tabs.details": "Chi tiết Giao dịch",
  "tradeForm.tabs.psychology": "Tâm lý & Ghi chú",
  "tradeForm.detailsDescription": "Hoàn tất tất cả các trường bắt buộc với thông tin chính xác để phân tích giao dịch tốt hơn. Thêm thời gian vào và ra chi tiết để theo dõi thời điểm thị trường.",
  "tradeForm.stockInfo": "Thông tin Chứng khoán",
  "tradeForm.stockSymbol": "Mã Chứng khoán",
  "tradeForm.stockSymbolPlaceholder": "ví dụ: VCB, FPT",
  "tradeForm.tradeDirection": "Hướng Giao dịch",
  "tradeForm.selectTradeType": "Chọn loại giao dịch",
  "tradeForm.buyLong": "Mua (Long)",
  "tradeForm.sellShort": "Bán (Short)",
  "tradeForm.entryInfo": "Thông tin Mở lệnh",
  "tradeForm.entryDate": "Ngày Mở lệnh",
  "tradeForm.entryTime": "Thời gian Mở lệnh",
  "tradeForm.whyTrackTime": "Tại sao phải theo dõi thời gian mở lệnh?",
  "tradeForm.timeTrackingBenefits": "Ghi lại thời gian mở lệnh giúp xác định mô hình trong giao dịch của bạn và thời gian thị trường tối ưu cho chiến lược của bạn.",
  "tradeForm.quantity": "Số lượng",
  "tradeForm.quantityPlaceholder": "ví dụ: 100",
  "tradeForm.entryPrice": "Giá Mở lệnh",
  "tradeForm.pricePlaceholder": "ví dụ: 150.25",
  "tradeForm.exitInfo": "Thông tin Đóng lệnh",
  "tradeForm.exitDate": "Ngày Đóng lệnh (Tùy chọn)",
  "tradeForm.pickExitDate": "Chọn ngày đóng lệnh",
  "tradeForm.exitTime": "Thời gian Đóng lệnh (Tùy chọn)",
  "tradeForm.exitPrice": "Giá Đóng lệnh (Tùy chọn)",
  "tradeForm.riskManagement": "Quản lý Rủi ro",
  "tradeForm.stopLossPrice": "Giá Cắt lỗ (Tùy chọn)",
  "tradeForm.stopLossDesc": "Giá mà bạn đã dự định thoát nếu giao dịch đi ngược lại bạn",
  "tradeForm.takeProfitPrice": "Giá Chốt lời (Tùy chọn)",
  "tradeForm.takeProfitDesc": "Giá mục tiêu để chốt lời",
  "tradeForm.tradingFees": "Phí Giao dịch (Tùy chọn)",
  "tradeForm.feesPlaceholder": "ví dụ: 5.00",
  "tradeForm.feesDesc": "Hoa hồng, phí sàn, v.v.",
  "tradeForm.psychologyDescription": "Ghi lại tâm lý và thiết lập của bạn giúp xác định mô hình trong hành vi giao dịch và cải thiện việc ra quyết định.",
  "tradeForm.tradingSetup": "Thiết lập Giao dịch",
  "tradeForm.setupPattern": "Mô hình/Thiết lập Giao dịch (Tùy chọn)",
  "tradeForm.selectPattern": "Chọn mô hình giao dịch",
  "tradeForm.patterns.breakout": "Breakout (Bứt phá)",
  "tradeForm.patterns.pullback": "Pullback (Điều chỉnh)",
  "tradeForm.patterns.trendFollowing": "Theo xu hướng",
  "tradeForm.patterns.reversal": "Đảo chiều",
  "tradeForm.patterns.gapFill": "Lấp khoảng trống",
  "tradeForm.patterns.supportResistance": "Hỗ trợ/Kháng cự",
  "tradeForm.patterns.earningsPlay": "Công bố lợi nhuận",
  "tradeForm.patterns.newsEvent": "Tin tức/Sự kiện",
  "tradeForm.patterns.other": "Khác",
  "tradeForm.setupDesc": "Mô hình hoặc thiết lập dẫn đến giao dịch này",
  "tradeForm.riskLevel": "Mức độ Rủi ro (Tùy chọn)",
  "tradeForm.selectRiskLevel": "Chọn mức độ rủi ro",
  "tradeForm.riskLevels.low": "Rủi ro Thấp",
  "tradeForm.riskLevels.medium": "Rủi ro Trung bình",
  "tradeForm.riskLevels.high": "Rủi ro Cao",
  "tradeForm.riskLevelDesc": "Mức độ rủi ro bạn cảm nhận cho giao dịch này",
  "tradeForm.psychology": "Tâm lý",
  "tradeForm.yourMood": "Tâm trạng của bạn (Tùy chọn)",
  "tradeForm.howWereYouFeeling": "Bạn cảm thấy thế nào?",
  "tradeForm.moods.calm": "Bình tĩnh",
  "tradeForm.moods.excited": "Phấn khích",
  "tradeForm.moods.anxious": "Lo lắng",
  "tradeForm.moods.confident": "Tự tin",
  "tradeForm.moods.unsure": "Không chắc chắn/Do dự",
  "tradeForm.moodDesc": "Trạng thái cảm xúc của bạn khi tham gia giao dịch này",
  "tradeForm.qualityRating": "Đánh giá Chất lượng (Tùy chọn)",
  "tradeForm.ratingDesc": "Bạn đánh giá chất lượng ra quyết định của mình như thế nào (1-5)",
  "tradeForm.tradeNotes": "Ghi chú Giao dịch (Tùy chọn)",
  "tradeForm.notesPlaceholder": "Tại sao bạn thực hiện giao dịch này, những gì bạn quan sát được, bài học kinh nghiệm...",
  "tradeForm.notesDesc": "Bao gồm các quan sát chính và bài học kinh nghiệm",
  "tradeForm.cancel": "Hủy",
  "tradeForm.saveChanges": "Lưu Thay đổi",
  "tradeForm.addTrade": "Thêm Giao dịch",
  "tradeForm.tradeUpdated": "Giao dịch Đã Cập nhật",
  "tradeForm.tradeUpdatedDesc": "Giao dịch của bạn đã được cập nhật thành công.",
  "tradeForm.tradeAdded": "Giao dịch Đã Thêm",
  "tradeForm.tradeAddedDesc": "Giao dịch mới đã được ghi lại thành công.",
  "tradeForm.strategyAndPsychology": "Chiến lược & Tâm lý",
  "tradeForm.choosePlaybook": "Chọn một chiến lược",
  "tradeForm.playbookDescription": "Chọn một chiến lược để liên kết với giao dịch này",
  "tradeForm.viewSelectedPlaybook": "Xem chiến lược đã chọn",
  "tradeForm.entryDateTime": "Ngày & Giờ Vào Lệnh",
  "tradeForm.exitDateTime": "Ngày & Giờ Thoát Lệnh",
  "tradeForm.dateTimeDescription": "Định dạng: DD/MM/YYYY HH:MM",
  "tradeForm.screenshots": "Ảnh chụp màn hình",
  "tradeForm.dropImageHere": "Kéo thả hình ảnh vào đây",
  "tradeForm.orClickToUpload": "hoặc nhấp để tải lên",
  "tradeForm.pasteScreenshot": "Bạn cũng có thể sử dụng Ctrl+V (hoặc Cmd+V) để dán trực tiếp ảnh chụp màn hình",
  "tradeForm.screenshotAdded": "Đã thêm ảnh chụp màn hình",
  "tradeForm.screenshotAddedDesc": "Ảnh chụp màn hình của bạn đã được thêm vào giao dịch",
  "tradeForm.zoomedScreenshot": "Ảnh chụp màn hình phóng to",
  "playbooks.title": "Chiến lược Giao dịch",
  "playbooks.description": "Ghi lại và theo dõi các chiến lược giao dịch của bạn để cải thiện tính nhất quán",
  "playbooks.addPlaybook": "Thêm Chiến lược",
  "playbooks.playbookList": "Danh sách Chiến lược",
  "playbooks.editPlaybook": "Sửa Chiến lược",
  "playbooks.createPlaybook": "Tạo Chiến lược",
  "playbooks.noPlaybooksYet": "Chưa có chiến lược nào",
  "playbooks.createFirstPlaybook": "Tạo chiến lược giao dịch đầu tiên của bạn để ghi lại chiến thuật của bạn.",
  "playbooks.winRate": "Tỷ lệ Thắng",
  "playbooks.avgRR": "Tỷ lệ R/R TB",
  "playbooks.timeframe": "Khung thời gian",
  "playbooks.na": "Không có",
  "playbooks.totalTrades": "Tổng Giao dịch",
  "playbooks.edit": "Sửa",
  "playbooks.stats": "Thống kê",
  "playbooks.delete": "Xóa",
  "playbooks.createNewPlaybook": "Tạo Chiến lược Mới",
  "playbooks.documentStrategyDesc": "Ghi lại chiến lược giao dịch của bạn với các quy tắc rõ ràng về thiết lập, mở lệnh và đóng lệnh.",
  "playbooks.playbookName": "Tên Chiến lược",
  "playbooks.playbookNamePlaceholder": "Ví dụ: Breakout Theo Xu hướng",
  "playbooks.selectTimeframe": "Chọn khung thời gian",
  "playbooks.timeframes.1min": "1 Phút",
  "playbooks.timeframes.5min": "5 Phút",
  "playbooks.timeframes.15min": "15 Phút",
  "playbooks.timeframes.30min": "30 Phút",
  "playbooks.timeframes.1hour": "1 Giờ",
  "playbooks.timeframes.4hour": "4 Giờ",
  "playbooks.timeframes.daily": "Hàng ngày",
  "playbooks.timeframes.weekly": "Hàng tuần",
  "playbooks.timeframes.monthly": "Hàng tháng",
  "playbooks.strategyDescription": "Mô tả Chiến lược",
  "playbooks.strategyPlaceholder": "Mô tả ngắn gọn chiến lược giao dịch của bạn...",
  "playbooks.setupCriteria": "Tiêu chí Thiết lập",
  "playbooks.setupCriteriaPlaceholder": "Bạn tìm kiếm những điều kiện thị trường hoặc chỉ báo nào?",
  "playbooks.entryTriggers": "Tín hiệu Mở lệnh",
  "playbooks.entryTriggersPlaceholder": "Điều gì là tín hiệu để bạn mở lệnh giao dịch?",
  "playbooks.exitRules": "Quy tắc Thoát lệnh",
  "playbooks.exitRulesPlaceholder": "Tiêu chí chốt lời và cắt lỗ của bạn là gì?",
  "playbooks.riskManagement": "Quản lý Rủi ro",
  "playbooks.riskManagementPlaceholder": "Mô tả quy tắc quản lý rủi ro và xác định khối lượng giao dịch của bạn...",
  "playbooks.additionalNotes": "Ghi chú Bổ sung",
  "playbooks.notesPlaceholder": "Bất kỳ thông tin quan trọng nào khác về chiến lược này...",
  "playbooks.cancel": "Hủy",
  "playbooks.updatePlaybook": "Cập nhật Chiến lược",
  "playbooks.savePlaybook": "Lưu Chiến lược",
  "playbooks.playbookUpdated": "Chiến lược đã cập nhật",
  "playbooks.playbookUpdatedDesc": "Đã cập nhật thành công chiến lược \"{name}\".",
  "playbooks.playbookCreated": "Chiến lược đã tạo",
  "playbooks.playbookCreatedDesc": "Đã tạo thành công chiến lược \"{name}\".",
  "playbooks.playbookDeleted": "Chiến lược đã xóa",
  "playbooks.playbookDeletedDesc": "Chiến lược đã được xóa.",
  "playbooks.list": "Danh sách",
  "playbooks.create": "Tạo mới",
  "playbooks.loadingPlaybooks": "Đang tải chiến lược...",
  "playbooks.errorLoadingPlaybooks": "Lỗi khi tải chiến lược",
  "playbooks.tryAgain": "Thử lại",
  "playbooks.confirmDelete": "Xác nhận xóa",
  "playbooks.confirmDeleteDesc": "Bạn có chắc chắn muốn xóa chiến lược này không? Hành động này không thể hoàn tác.",
  "playbooks.statisticsAndAnalysis": "Thống kê và Phân tích",
  "playbooks.close": "Đóng",
  "playbooks.overview": "Tổng quan",
  "playbooks.charts": "Biểu đồ",
  "playbooks.performanceMetrics": "Chỉ số hiệu suất",
  "playbooks.streaksAndTiming": "Chu kỳ và thời gian",
  "playbooks.tradeResults": "Kết quả giao dịch",
  "playbooks.winLossRatio": "Tỷ lệ thắng/thua",
  "playbooks.winLossRatioDesc": "So sánh số lượng giao dịch thắng và thua của chiến lược này",
  "playbooks.monthlyPerformance": "Hiệu suất theo tháng",
  "playbooks.monthlyPerformanceDesc": "Xu hướng lợi nhuận và số lượng giao dịch theo từng tháng",
  "playbooks.consecutiveWins": "Thắng liên tiếp",
  "playbooks.consecutiveLosses": "Thua liên tiếp",
  "playbooks.avgHoldingTime": "Thời gian giữ TB",
  "playbooks.totalWins": "Tổng thắng",
  "playbooks.totalLosses": "Tổng thua",
  "playbooks.bestTrade": "Giao dịch tốt nhất",
  "playbooks.worstTrade": "Giao dịch tệ nhất",
  "playbooks.profitFactor": "Hệ số lợi nhuận",
  "playbooks.wins": "Thắng",
  "playbooks.losses": "Thua",
  "playbooks.profit": "Lợi nhuận",
  "playbooks.trades": "Giao dịch",
  "playbooks.noData": "Không có dữ liệu",
  "playbooks.noTradesForChart": "Không có dữ liệu giao dịch để hiển thị biểu đồ",
  "playbooks.noTradesYet": "Chưa có giao dịch nào cho chiến lược này",
  "playbooks.addTradesHint": "Thêm giao dịch với chiến lược này để xem thống kê chi tiết",
  "playbooks.timeframes.1h": "1 Giờ",
  "playbooks.timeframes.4h": "4 Giờ",
  "playbooks.timeframes.1d": "1 Ngày",
  "journals.title": "Nhật ký Giao dịch",
  "journals.description": "Quản lý nhật ký giao dịch và theo dõi hiệu suất riêng cho các chiến lược và tài khoản khác nhau",
  "journals.createNew": "Tạo mới",
  "journals.searchJournals": "Tìm kiếm nhật ký...",
  "journals.sort": "Sắp xếp",
  "journals.sortNewest": "Mới nhất trước",
  "journals.sortOldest": "Cũ nhất trước",
  "journals.sortNameAsc": "Tên A-Z",
  "journals.sortNameDesc": "Tên Z-A",
  "journals.sortMostTrades": "Nhiều giao dịch nhất",
  "journals.filterButton": "Lọc",
  "journals.allJournals": "Tất cả nhật ký",
  "journals.activeJournals": "Nhật ký đang hoạt động",
  "journals.templates": "Mẫu",
  "journals.noJournalsFound": "Không tìm thấy nhật ký nào",
  "journals.noJournalsFoundDesc": "Bạn chưa có nhật ký nào. Tạo nhật ký đầu tiên để bắt đầu.",
  "journals.createFirst": "Tạo nhật ký đầu tiên",
  "journals.trades": "Giao dịch",
  "journals.winRate": "Tỷ lệ thắng",
  "journals.openTrades": "Giao dịch mở",
  "journals.lastActivity": "Hoạt động gần đây",
  "journals.never": "Chưa bao giờ",
  "journals.viewDashboard": "Xem bảng điều khiển",
  "journals.switchTo": "Chuyển đến nhật ký",
  "journals.useTemplate": "Sử dụng mẫu",
  "journals.template": "Mẫu",
  "journals.default": "Mặc định",
  "journals.created": "Đã tạo",
  "journals.actions": "Hành động",
  "journals.currentlyActive": "Đang hoạt động",
  "journals.edit": "Sửa nhật ký",
  "journals.settings": "Cài đặt nhật ký",
  "journals.duplicate": "Sao chép nhật ký",
  "journals.delete": "Xóa nhật ký",
  "journals.noActiveJournals": "Không có nhật ký đang hoạt động",
  "journals.noActiveJournalsDesc": "Bạn chưa có nhật ký đang hoạt động nào. Tạo nhật ký mới để bắt đầu.",
  "journals.createJournal": "Tạo nhật ký",
  "journals.noTemplatesFound": "Không tìm thấy mẫu nào",
  "journals.noTemplatesFoundDesc": "Hiện không có mẫu nhật ký nào.",
  "journals.currency": "Tiền tệ",
  "journals.initialCapital": "Vốn ban đầu",
  "journals.initialCapitalPlaceholder": "ví dụ: 10000",
  "journals.riskPercentage": "Tỷ lệ rủi ro",
  "journals.tradingHours": "Giờ giao dịch",
  "journals.confirmDelete": "Xóa nhật ký",
  "journals.confirmDeleteDesc": "Bạn có chắc chắn muốn xóa nhật ký này không? Hành động này không thể hoàn tác.",
  "journals.warningTitle": "Cảnh báo",
  "journals.warningDesc": "Xóa nhật ký này sẽ xóa vĩnh viễn tất cả giao dịch và dữ liệu liên quan.",
  "journals.createNewJournal": "Tạo nhật ký mới",
  "journals.createNewJournalDesc": "Đặt tên và mô tả cho nhật ký để giúp bạn nhận dạng nó.",
  "journals.name": "Tên nhật ký",
  "journals.namePlaceholder": "ví dụ: Giao dịch Cổ phiếu 2025",
  "journals.description": "Mô tả (Tùy chọn)",
  "journals.descriptionPlaceholder": "ví dụ: Nhật ký giao dịch cổ phiếu cho các giao dịch swing",
  "journals.icon": "Biểu tượng",
  "journals.selectIcon": "Chọn biểu tượng",
  "journals.icons.chart": "Biểu đồ",
  "journals.icons.trendingUp": "Xu hướng tăng",
  "journals.icons.activity": "Hoạt động",
  "journals.icons.globe": "Toàn cầu",
  "journals.icons.bitcoin": "Bitcoin",
  "journals.color": "Màu sắc",
  "journals.create": "Tạo nhật ký",
  "journals.journalCreated": "Đã tạo nhật ký",
  "journals.journalCreatedDesc": "Nhật ký giao dịch mới của bạn đã được tạo thành công.",
  "journals.journalDeleted": "Đã xóa nhật ký",
  "journals.journalDeletedDesc": "Nhật ký của bạn đã được xóa thành công.",
  "journals.templateCreated": "Đã tạo nhật ký từ mẫu",
  "journals.templateCreatedDesc": "Nhật ký mới của bạn đã được tạo từ mẫu.",
  "journals.journalUpdated": "Đã cập nhật nhật ký",
  "journals.journalUpdatedDesc": "Nhật ký giao dịch của bạn đã được cập nhật thành công.",
  "journals.update": "Cập nhật",
  "journals.editJournal": "Chỉnh sửa nhật ký",
  "journals.editJournalDesc": "Cập nhật thông tin cơ bản của nhật ký giao dịch.",
  "journals.errors.nameRequired": "Tên nhật ký là bắt buộc",
  "journals.errors.nameRequiredDesc": "Vui lòng nhập tên cho nhật ký giao dịch của bạn.",
  "journals.errors.cannotDeleteLast": "Không thể xóa nhật ký cuối cùng",
  "journals.errors.cannotDeleteLastDesc": "Bạn phải có ít nhất một nhật ký. Tạo nhật ký mới trước khi xóa nhật ký này.",
  "common.cancel": "Hủy",
  "common.loading": "Đang tải...",
};

interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Hàm dịch đơn giản hóa - luôn trả về tiếng Việt
  const t = (key: string): string => {
    const translation = translations[key];
    
    if (translation) {
      return translation;
    }
    
    // Xử lý trường hợp key có dạng phân cấp như "tradeForm.selectPlaybook"
    const parts = key.split('.');
    if (parts.length > 1) {
      let currentKey = '';
      for (let i = 0; i < parts.length; i++) {
        currentKey += (i === 0 ? '' : '.') + parts[i];
        if (translations[currentKey]) {
          return translations[currentKey];
        }
      }
    }
    
    // Hiển thị cảnh báo trong console và trả về key gốc
    console.warn(`Translation key "${key}" not found.`);
    return key;
  };

  const value = {
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

// Hook để sử dụng context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};